### ISSUE TITLE
Compatibility on newer devices.

### ISSUE THREAD

**Issue by doraorak** [PoomSmart/Amber#11]
Hello i have an iphone 14 pro max on ios 16.5. I am using roothide bootstrap and serotonin semi-jailbreak but when i install this tweak i can change between the modes (white amber all) fine but it doesn't seem to change the color of the flashlight. My theory is newer devices don't have this amber led at all (but i couldn't find any info about it). Or its unsupported on newer ios versions (and maybe because serotonin is not a full jailbreak). Thanks in advance for any info you can give.

**Comment by PoomSmart** [comment]
Because it's not a full jailbreak and that means hooking `mediaserverd` process isn't possible. That hooking is required by this tweak.
