### ISSUE TITLE
Amber crashing mediaserverd on an iPhone 12 Pro

### ISSUE THREAD

**Issue by absidue** [PoomSmart/Amber#3]
When Amber is enabled, turning on the torch crashes mediaserverd and then the torch turns back off, after that the torch will behave as if Amber was never enabled (just white LEDs) until the next respring, when it starts from the start again.

**Device info**:
Model: iPhone 12 Pro
iOS version: 14.3 RC1
Jailbreak: Taurine 1.0.4
Hooking framework: libhooker 1.6.0

**mediaserverd crashlog**
https://pastebin.com/PFJs18FA

**Comment by PoomSmart** [comment]
@absidue Could you try the debug version of Amber? This should be easier to debug.
[com.ps.amber_0.0.5_iphoneos-arm.deb.zip](https://github.com/PoomSmart/Amber/files/6365939/com.ps.amber_0.0.5_iphoneos-arm.deb.zip)

**Comment by absidue** [comment]
These crashlogs are with the debug build, I'll check the syslog when I get to my computer.

When turning the torch on from the control center: https://pastebin.com/cLU9BGQT

Turning the torch on from button on the cover sheet / lock screen: https://pastebin.com/dv0QPp68

**Comment by PoomSmart** [comment]
@absidue Here I fixed an issue where some symbols won't be found. Please help test.
[com.ps.amber_0.0.5_iphoneos-arm.deb.zip](https://github.com/PoomSmart/Amber/files/6369173/com.ps.amber_0.0.5_iphoneos-arm.deb.zip)

**Comment by absidue** [comment]
@PoomSmart That build fixes the crashes and makes it work again, THANK YOU!

The only issue that I just noticed is that activating all LEDs from the control center (swiping up next to the expanded torch view) won't show any change on the UI even though it activates all LEDs.

**Comment by PoomSmart** [comment]
@absidue I fixed that in the release version of Amber (0.0.5), you can go refresh my repo and reinstall it.

**Comment by PoomSmart** [comment]
Resolved.

**Comment by PoomSmart** [comment]
Resolved.

**Comment by absidue** [comment]
Thanks for fixing it so quickly :).
