### ISSUE TITLE
Springboard sometimes crashing when turning on flashlight from control center

### ISSUE THREAD

**Issue by ElioFegh** [PoomSmart/Amber#6]

**Comment by PoomSmart** [comment]
Crash log?

**Comment by ElioFegh** [comment]
> Crash log?

Yeah sorry, but I didn't have cr4shed earlier, I installed it yesterday and if I encounter it again I'll share the log here (ig there's something that has to do with amberSpringboard). Btw just wanted to say that you're the best dev in this community! Thanks for all this awesome work!

**Comment by ElioFegh** [comment]
Hey, so it looks like it's not happening anymore. Maybe it was a conflict with another tweak or something. Anyway thank you for trying to solve the issue! I will close this issue and if it ever happens again, I will be providing a crash log with it
