### ISSUE TITLE
iOS 15 palera1n jailbreak

### ISSUE THREAD

**Issue by rkinlen** [PoomSmart/Amber#7]
After install of amber and CCsupport and respring no amber icon is available  to be added to control centre. I have tested with no other tweaks installed and still the same issue. This may very well be me doing something wrong as on the iOS 15 compatible tweaks list is working fine for forget people, I am on iOS 15.1 iPhone 8.
Many thanks Rory

**Comment by PoomSmart** [comment]
Invalid issue. Read the tweak description.
