### ISSUE TITLE
Installing, rebooting, then rejailbreaking breaks Amber

### ISSUE THREAD

**Issue by NotDarkn** [PoomSmart/Amber#8]
**Jailbreak:**
Fugu15 Max

Upon first installation of Amber, it seems to function as normal and correctly.

If the user reboots their device and then rejailbreaks, Amber no longer works.

The current fix I found for this was to reinstall Amber and then check if it works.

This seems to be an issue with just Fugu15 Max, as this wasn’t an issue when using XinaA15.

**Comment by PoomSmart** [comment]
Jailbreak issue. Existing daemons (mediaserverd in this case) won't be injected automatically after jailbreak. Reinstalling is the correct workaround.

Issue invalid.

**Comment by NotDarkn** [comment]
fair enough lol
